### ISSUE TITLE
excluding namespaces in a multi-tenant kubernetes environment

### ISSUE THREAD

**Issue by JonasSame** [IBM/ibm-licensing-operator#207]
Hi,
we have a feature request to be able to exclude namespaces in a multi-tenant kubernetes cluster. For compliance reasons we can't allow the license operator to scan all namespaces in our AKS cluster. We have tried modifying the role binding for the service account but the software fails.
This feature would be greatly appreciated so that we can monitor the license usage only for the IBM related namespaces in our cluster.
Thanks in advance!

//Jonas

**Comment by pgodowski** [comment]
@JonasSame thanks for opening this issue. To move forward with this conversation, please reach out to IBM via your IBM account team, we'd like to learn more about your scenarios first.

**Comment by JonasSame** [comment]
We would like to know under what product a support request is opened in this case, we could not find any suitable product.
Br/Jonas

**Comment by pgodowski** [comment]
Please open a support Case on the IBM product that you need track license usage on your environment and mention that the IBM License Service team needs to be contacted.

**Comment by JonasSame** [comment]
Thanks! ticket sent in, can you please leave this issue open a while since I am referring to this thread in the case. Cheers!

**Comment by pgodowski** [comment]
Ticket arrived on our side, let's continue the conversation via appropriate channel. Closing for now.
