### ISSUE TITLE
AKS installation - Role / API issues

### ISSUE THREAD

**Issue by jcamu** [IBM/ibm-licensing-operator#332]
Hello,

In order to follow new licencing rules, we tried installation of ibm-licensing-operator in AKS Rbac enabled cluster.
We tried to install License Service for stand-alone IBM Containerized Software without IBM Cloud Paks.

Apparently there is issues with roles and roleBinding.

Some additional rules seems needed at cluster scope.

Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:ibm-common-services:ibm-licensing-operator" cannot list resource "deployments" in API group "apps" at the cluster scope
Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:serviceaccount:ibm-common-services:ibm-licensing-operator" cannot list resource "services" in API group "" at the cluster scope
Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:ibm-common-services:ibm-licensing-operator" cannot list resource "secrets" in API group "" at the cluster scope
.....

We need this rule to be at cluster scope level so in clusterRole ibm-licensing-operator
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  -

The ibm-license-service is not in the role.yaml file but in role_operand.yaml

The documentation seems incorrect, the same with the tag to use when we clone the repo.

Once done how to contact this service to retrieve data? Snapshot?
Only calling the service thanks to ingress seems not to work.
even calling the /version return an malformed response

Regards,

**Comment by jcamu** [comment]
We change and used the last version 1.4.2 and still need to update the roles but now the api is working

See issue [367](https://github.com/IBM/ibm-licensing-operator/issues/367)

**Comment by bcp2021** [comment]
Had the same issues but then from onprem installation.
The solution is in the role.yaml.

Some permissions are missing:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
