### ISSUE TITLE
No product found/ Empty audit snapshot

### ISSUE THREAD

**Issue by jcamu** [IBM/ibm-licensing-operator#367]
Hello,

We installed the ibm-licensing-operator following documentation below

https://github.com/IBM/ibm-licensing-operator/blob/release-1.4/docs/Content/Install_without_OLM.md

We make a simple by deploying websphere-liberty on AKS based on  dockerfile like below ..
'FROM websphere-liberty:kernel
...

RUN configure.sh

EXPOSE 9080
'

The snapshop is download but all excels are empty, 
Bundle and products reports return [].

Is there something missing? Did we need to activate specific feature ? 

What should be in unrecognized-apps ? It's linked to IBM resources or to list others apps, deployment withour IBM products?
This file is empty too.

Thanks in advance.

Regards,

**Comment by pgodowski** [comment]
Hi @jcamu can you please open the IBM Support ticket againt the IBM Product you are looking to track license usage (perhaps it is Websphere Liberty), to get this issue resolved?
